### PR TITLE
RP1 VEC: Use tv_mode from command line, align enum with drm_connector; tidy

### LINKED ISSUE #5864: RP1 VEC: "tv_mode" property is not correctly inherited from command line "video"
### Describe the bug

RP1 VEC has a `tv_norm` string parameter which affects
- The set of named DRM modes advertised
- The colour system and pedestal used in some of those modes

(by default it supports all TV modes, prefers NTSC, and guesses NTSC or PAL depending on the active mode).

It can successfully be set as a module parameter from the command line (so there is no urgent problem). However, the more standard `video/tv_mode` command line setting appears to be ignored.

Furthermore, the private enum of tv_norms used by RP1 VEC driver does not quite match DRM's `enum drm_connector_tv_mode`.  It would cause confusion if an enumerated value were to get passed from the connector to our driver (which we do at least _attempt_ to do, via `drm_object_attach_property()`). The same thing is true for VC4 VEC.

### Steps to reproduce the behaviour

When using RP1 VEC, compare different behaviour between
`video=Composite-1,tv_mode=NTSC-J`
and
`video=Composite-1 drm-rp1-vec.tv_norm=NTSC-J`

### Device (s)

Other

### System

Raspberry Pi 5
rpi-6.1.y as at Thu 18 Jan 11:32:27 GMT 2024

### Logs

_No response_

### Additional context

May also be relevant to VC4.

### PR DESCRIPTION
**Pull request by njhollinghurst**
This attempts to fix #5864, targeting Linux 6.6

I narrowly kept the "tv_norm" module parameter  in this draft; but it's somewhat redundant now that we can use video/tv_mode.

### CODE REVIEW

**Comment by njhollinghurst** [comment]
@6by9  Shall I go ahead and remove the "tv_norm" parameter altogether? I am in two minds about it. 

(I think the VEC driver will need at least one parameter, either for enabling 'vintage' modes and/or defining a custom mode, prior to evaluating the "video=" mode; but it need not be the existing "tv_norm" parameter.)

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c [hunk 1]
```diff
@@ -231,36 +198,47 @@ static const struct drm_display_mode rp1vec_modes[4] = {
 	}
 };
 
+/*
+ * Advertise standard and preferred video modes.
+ *
+ * From each interlaced mode in the table above, derive a progressive one.
+ *
+ * This driver always support all 50Hz and 60Hz video modes, regardless
```
Comment (6by9) [inline drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: nit: s/support/supports

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c [hunk 2]
```diff
@@ -231,36 +198,47 @@ static const struct drm_display_mode rp1vec_modes[4] = {
...
+ * (except that "PAL" with 525/60 will be implemented as "PAL60").
+ */
+
 static int rp1vec_connector_get_modes(struct drm_connector *connector)
 {
-	struct rp1_vec *vec = container_of(connector, struct rp1_vec, connector);
-	bool ok525 = RP1VEC_TVSTD_SUPPORT_525(vec->tv_norm);
-	bool ok625 = RP1VEC_TVSTD_SUPPORT_625(vec->tv_norm);
 	int i, prog, n = 0;
+	int tvm = rp1vec_initial_tv_mode(connector);
```
Comment (6by9) [inline drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: Do we really want the command line tv_norm here, or use the currently selected standard?

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c [hunk 3]
```diff
@@ -269,11 +247,9 @@ static int rp1vec_connector_get_modes(struct drm_connector *connector)
 
 static void rp1vec_connector_reset(struct drm_connector *connector)
 {
-	struct rp1_vec *vec = container_of(connector, struct rp1_vec, connector);
-
 	drm_atomic_helper_connector_reset(connector);
 	if (connector->state)
-		connector->state->tv.mode = vec->tv_norm;
+		connector->state->tv.mode = rp1vec_initial_tv_mode(connector);
```
Comment (6by9) [inline drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: I'd need to check when the connector state reset is used. It feels like we really want to take the value from the DRM property, not the original default.

If it comes from the DRM property, then it feels better to do it in the framework reset, not the driver specific one. I vaguely recall having to fix up the planes reset for colourspace or rotation previously for the same reasons.

Actually `drm_atomic_helper_connector_tv_reset` uses exactly that, although a downstream patch then messes that up.

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c [hunk 4]
```diff
@@ -231,36 +198,47 @@ static const struct drm_display_mode rp1vec_modes[4] = {
...
-				}
-
-				if (mode->hdisplay == 704 &&
-				    mode->vtotal == ((ok525) ? 525 : 625))
-					mode->type |= DRM_MODE_TYPE_PREFERRED;
-
-				drm_mode_set_name(mode);
-				drm_mode_probed_add(connector, mode);
-				n++;
+		for (prog = 0; prog < 2; prog++) {
```
Comment (6by9) [inline drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: The default timings for the defined TV standards can added with
```
	int count = drm_connector_helper_tv_get_modes(connector);
```
vc4 does this in the 6.6 tree.

Adding the cropped modes is a little trickier and may still require modes to be stored, but it's nicer to remove as much duplication as possible.

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 2 above)
Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: I wasn't sure... the latter is in "state" which I thought might have locking issues?
The only thing it affects is which mode is marked as "preferred".

Comment (6by9) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: Use `drm_connector_helper_tv_get_modes` and let it worry about which one gets the preferred flag set.

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 4 above)
Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: Gosh there's a lot of code under `drm_connector_helper_tv_modes()`. Hope it's correct.
Will it produce both 525/60 and 625/50 modes at the same time?

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 3 above)
Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: OK. I'm a bit vague as to the difference between the "default value", the "property value" and the "state", and what is the intention of the reset, but it looks like we should follow (or maybe just call) `drm_atomic_helper_connector_tv_reset()`

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 2 above)
Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: ...or should it do as discussed below and use `drm_object_property_get_default_value()`?

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 4 above)
Comment (6by9) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: Maxime wrote it

It'll add 480i and/or 576i based on the standards listed `drm_mode_create_tv_properties` was told were supported, and in the order (+ preferred flag) as based on the default value registered when you `drm_object_attach_property` the tv_mode property.

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 2 above)
Comment (6by9) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c]: Discussed below. Resolving.

File: drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c (hunk 4 above)
Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: Ah, so that's what "default property value" means.

Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: Currently marking one of the cropped modes as "preferred": this is to stop the FB console spilling off the screen (in the absence of any better way of handling overscan).

As I've just checked, `drm_connector_helper_tv_modes()` does return both Rec.601 modes, though not the progressive ones (maybe that needs an extra command line option). Is there a way to stop it marking one of those as preferred?

Comment (6by9) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: The cropped modes being preferred probably does mean you need to roll your own.

I seem to recall there is a function to nuke the preferred flag from all modes so you can add it as you see fit, but it may or may not help.

Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: I just tried an experiment to see if that helper function would pay attention to "margin_left" etc. Unsurprisingly it seems not to. I think I may need to roll my own. I'll ensure the standard modes match its output (one of my porches differs by all of 4 pixels right now).

I'll tidy up the preferred flag, to use the property's own default rather than go back to the command line options.

Comment (njhollinghurst) [reply drivers/gpu/drm/rp1/rp1-vec/rp1_vec.c:214]: I think it's as good as it's going to get, for now.

Will look at it again when we add the "vintage" TV modes (for which a "progressive" variant is probably not useful).

**Comment by njhollinghurst** [comment]
Cherry-picked this back onto the rebased rpi-6.6.y. Will do a quick re-test and then merge.
